### ISSUE TITLE
IOError trying to create a JS9 object

### ISSUE THREAD

**Issue by cdeil** [ericmandel/pyjs9#2]
I was trying to follow the instructions in the `README`, but there's an `IOError` when I try to create the `JS9` object:

``` python
In [3]: j = pyjs9.JS9()
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-3-80d086fc1bbf> in <module>()
----> 1 j = pyjs9.JS9()

/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.pyc in __init__(self, host, id)
    197             host = 'http://' + host
    198         self.__dict__['host']  = host
--> 199         self._alive()
    200 
    201     def __setitem__(self, itemname, value):

/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.pyc in _alive(self)
    211         An internal routine to send a test message to the helper
    212         """
--> 213         self.send(None, msg="image")
    214 
    215     def send(self, obj, msg='msg'):

/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.pyc in send(self, obj, msg)
    233             url = urllib.urlopen(self.host + '/' + msg, jstr)
    234         except IOError as e:
--> 235             raise IOError,  "{0}: {1}".format(self.host, e.strerror)
    236         urtn = url.read()
    237         if urtn[0:6] == 'ERROR:':

IOError: http://localhost:2718: [Errno 61] Connection refused

In [4]: j = pyjs9.JS9('js.si.edu')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-4-e049813b7ad3> in <module>()
----> 1 j = pyjs9.JS9('js.si.edu')

/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.pyc in __init__(self, host, id)
    197             host = 'http://' + host
    198         self.__dict__['host']  = host
--> 199         self._alive()
    200 
    201     def __setitem__(self, itemname, value):

/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.pyc in _alive(self)
    211         An internal routine to send a test message to the helper
    212         """
--> 213         self.send(None, msg="image")
    214 
    215     def send(self, obj, msg='msg'):

/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.pyc in send(self, obj, msg)
    233             url = urllib.urlopen(self.host + '/' + msg, jstr)
    234         except IOError as e:
--> 235             raise IOError,  "{0}: {1}".format(self.host, e.strerror)
    236         urtn = url.read()
    237         if urtn[0:6] == 'ERROR:':

IOError: http://js.si.edu:2718: [Errno 8] nodename nor servname provided, or not known
```

I guess I need to install and maybe launch `JS9` first?
Can't `pysd9` do this for me (like e.g. `ipython notebook` does)?

**Comment by ericmandel** [comment]
The default behavior is to try to connect to a localhost js9 helper, since that seems to be the most useful target. Presumably you do not have js9helper running on your local machine. Perhaps this should not be the default? But if so, what should be the default?

In the second case, try:

> > >  j = pyjs9.JS9('js9.si.edu')
> > > instead of:
> > > j = pyjs9.JS9('js.si.edu')

That should succeed, since there is a back-end helper listening for connections. Note that, without bringing up the page itself in a browser, this won't do you much good:

> > > j = pyjs9.JS9('js9.si.edu')
> > > j.cmap()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/**init**.py", line 1445, in cmap
> > >     return self.send({"cmd": "cmap", "args": args})
> > >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/**init**.py", line 238, in send
> > >     raise ValueError, urtn
> > > ValueError: ERROR: 0 JS9 instance(s) found with id JS9 (cmap)

However, if you now load js9.si.edu into your browser, things will work better:

> > > j.cmap()
> > > 'grey 1.75 0.8'

So the idea is that you connect to the server (default: on localhost), with or without a page being loaded, and interact with a js9-enabled page when its loaded.

I'm open to doing this differently, of course. For example, should the js9() method try to load a page into your browser automatically -- in the same way that pyds9 starts up ds9 if it is not already running? If so, which page gets loaded? And how do we guarantee that the helper is running, etc?

**Comment by cdeil** [comment]
Thanks for the explanations.

I think opening some default webpage and starting a `js9helper` locally to make this "just work" would be nice.

But the issue I had was that I wanted to try out the example Python commands at
https://github.com/ericmandel/pyjs9/blob/master/README.rst
and overlooked that I have to start a `js9helper`.

Can you describe how to do that in the `pyjs9` docs or (maybe better) point to the right place in the `js9` docs how to do this?

**Comment by cdeil** [comment]
I can't test with the `js9` server ... it times out after a minute:

``` python
$ time python2.7 -c 'import pyjs9; pyjs9.JS9("js9.si.edu")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.py", line 199, in __init__
    self._alive()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.py", line 213, in _alive
    self.send(None, msg="image")
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.py", line 235, in send
    raise IOError,  "{0}: {1}".format(self.host, e.strerror)
IOError: http://js9.si.edu:2718: [Errno 60] Operation timed out

real    1m15.458s
user    0m0.173s
sys 0m0.098s
```

Probably port 2718 is blocked in my network for security reasons.
A lot of people will run into that issue if you use a non-standard port.
Can't you just use the normal HTTP / HTTPS port by default for communication?

**Comment by ericmandel** [comment]
[I will improve the pyjs9 docs, as requested.]

Are you saying that your network blocks outgoing connects to 2718? That's awkward!

We can't use HTTP port 80 for the helper, because the helper is meant to run along-side a Web server and the Web server itself uses that port. That is what is happening at js9.si.edu, for example. There is no hope of getting random site admins to support socket.io inside their Web servers, so the helper functionality has to be separate.

Of course, the helper port used is a parameter. I changed it to 8080 on my test server:

http://mred1.cfa.harvard.edu

Try testing against this server. The web page to load is: 

http://mred1.cfa.harvard.edu/js9/js9debug.html

NB: this site contains not yet released JS9 code. It contains full incorporation of the cfitsio library into JS9 (using emscripten to compile to javascript) and is still being tested for a March release ... I hope.

**Comment by cdeil** [comment]
Both `JS9("http://mred1.cfa.harvard.edu")` and `JS9("http://mred1.cfa.harvard.edu:8080")` time out for me. Most likely the issue is on my end in the network config.

However at the bottom of the page http://js9.si.edu/js9/help/helper.html I found that I can use this to start the `jsHelper.js` locally ... I think this is all I need to start playing with `pyjs9`:

```
node js9Helper.js 
```

PS: https://readthedocs.org/ is awesome ... it auto-builds your docs on every commit to Github, has full-text search, nice layout, a Javascript applet to switch between versions, .... see e.g. http://astropy.readthedocs.org/en/latest/ . :-)

**Comment by ericmandel** [comment]
Port 80 on mred1 is a Web server, so that won't work. But 8080 should work. If you find the problem, please let me know. I might have to think of another option for listening on a helper port if users are going to be blocked from connecting to anything but port 80. Not sure what but ...

Right, as you say, you should be able to start node up and use the defaults in js9Prefs.json which come with the distro.

I'll look at readthedocs.org before the next JS9 release (i.e. when I am actively working on final documentation). Thanks!

**Comment by cdeil** [comment]
When you're working on the docs, could you please change

``` python
from pyjs9 import *
```

to

``` python
from pyjs9 import JS9
```

?

`import *` makes it often hard to debug issues when using many packages because it can overwrite symbols, and it makes code more difficult to read because it's not obvious which symbol came from which package.

**Comment by jberlanga** [comment]
I'll make a separate issue for @cdeil 's last comment since it's an easy fix.
